### ISSUE TITLE
Ship image URL

### ISSUE THREAD

**Issue by philipengberg** [r-spacex/SpaceX-API#158]
Would it be possible to add an image url to `/ships`? Maybe just use the one form marinetraffic.com if there are no legal issues?

**Comment by jakewmeyer** [comment]
Looking into this

**Comment by jakewmeyer** [comment]
We should be good on the legality issue because the photos have a copyright watermark with credit to the photographer and the web source included. MarineTraffic also states that anyone using the image links does not gain the photo rights, but has permission to use them, as long as the watermark is present. 

Any preference on image size?

**Comment by philipengberg** [comment]
Awesome 🎉 The easiest for you is just to use the original size I guess? Then clients can downsize them as they please. It's hard to go the other way 😉

**Comment by jakewmeyer** [comment]
Agreed. I'll let you know once it's added 👍

**Comment by jakewmeyer** [comment]
Images added

**Comment by philipengberg** [comment]
🚢🎉 Party all day
