### ISSUE TITLE
Wrong order in upcoming launches

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#197]
It seems that upcoming launches from the CCtCap Demo to CRS-17 are unordered, compared to the launch [manifest](https://www.reddit.com/r/spacex/wiki/launches/manifest).

**Comment by petrosh** [comment]
If I can join, CRS-19 has
```
  "launch_year": "2018",
  "launch_date_unix": 1539604800,
  "launch_date_utc": "2018-10-15T12:00:00.000Z",
  "launch_date_local": "2018-10-15T08:00:00-04:00",
  "is_tentative": true,
  "tentative_max_precision": "day"
```
and every upcoming launch has is_tentative: true so I don't know how to deal with launch_date_local, for example with SARah 1 "2018-12-31T16:00:00-08:00"

Thanks

**Comment by jakewmeyer** [comment]
Reverted the change from last night that caused this. Everything was working fine until the manifest showed `2019 Early Feb` which didn't work well with the current date parser. So in an effort to prevent it from happening again, I tried adding a natural language date parser to try and parse any weird stuff thrown at it, and it seemed like it was working, but apparently not.

@petrosh It used to be hell to update, but the script does all the heavy lifting now since late September. Up until now the manifest has been extremely predictable, and relatively easy to parse. But it doesn't take much to break it unfortunately. Closest thing to a NET flag is the `is_tentative` flag, which becomes true when a launch has a time listed. Some people also check the `tentative_max_precision` field, and if it shows `month` or greater it could be considered NET.

**Comment by jesusrp98** [comment]
Yeah! Now, all upcoming launches have a correct launch date, expect the CCtCap Demo Mission: It's scheduled to January 2019. 

Since in the launch manifest it's listed as `2019 Early Feb`, would it be possible to change mission's launch date to `2019 Feb`?

**Comment by jakewmeyer** [comment]
Just went ahead an added a regex replace for `early`, `mid`,  and `late`. Just strips that from that date, since we can't really represent it in date form.

**Comment by jesusrp98** [comment]
That's great! As always, thanks for all! :)
