### ISSUE TITLE
Upcoming Launch Data out of date

### ISSUE THREAD

**Issue by timisenman** [r-spacex/SpaceX-API#208]
For launches 77 and 78, I'm getting these dates in the JSON:

```
"launch_date_unix": 1551398400,
"launch_date_utc": "2019-03-01T00:00:00.000Z",
"launch_date_local": "2019-02-28T16:00:00-08:00"
```

It's both in the past, and duplicated across the two launches. Not sure if it's an issue with the API, or the data source.

**Comment by jakewmeyer** [comment]
So this has to do with partial date representation.

The data is being pulled in from the subreddit wiki [manifest](https://www.reddit.com/r/spacex/wiki/launches/manifest), which has both launches as `2019 Mar`. So the date parser assumes the first of the month for the utc and unix times, and the time zone offset is subtracted from that , depending on the launch location. 

Our solution for this is the `tentative_max_precision` field, which can be `[ 'year', 'half', 'quarter', 'month', 'day', 'hour' ]` to show the precision of the partial date. So in this case, because both launches have a max precision of `month`, we would only display the date up to a month representation, or `2019 Mar`.
