### ISSUE TITLE
Invalid work of "missions" filter in cores and capsules endpoint

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#241]
Seems that "missions" filter doesn't work when trying to use in Capsules or Cores endpoint. Examples:
https://api.spacexdata.com/v3/capsules?missions=CRS-2
https://api.spacexdata.com/v3/cores?missions=ZUMA

Both of them returns full lists.

**Comment by jakewmeyer** [comment]
Typo in the docs. Should be `mission` instead of `missions`.

[https://api.spacexdata.com/v3/capsules?mission=CRS-2](https://api.spacexdata.com/v3/capsules?mission=CRS-2)
[https://api.spacexdata.com/v3/cores?mission=ZUMA](https://api.spacexdata.com/v3/capsules?mission=CRS-2)

Docs have been updated 👍

**Comment by Tearth** [comment]
Thanx!
