### ISSUE TITLE
Performance issue with /launches/all

### ISSUE THREAD

**Issue by Tearth** [r-spacex/SpaceX-API#247]
It's not the bug, but I just want to let you know about it. When trying to retrieve data from the https://api.spacexdata.com/v2/launches/all endpoint, it usually takes a few seconds (from 4 to 8) before the data is received, so quite long. I assume that it's because of the launches count, but maybe some sort of cache would be helpful with shortening waiting time?

![Screenshot_1](https://user-images.githubusercontent.com/26147774/62863965-b5dd1b80-bd0a-11e9-813c-7515c583a00f.png)

**Comment by jakewmeyer** [comment]
Looks like we might be outgrowing the current VM hosting the project.

There's been a massive influx of traffic this month, and the nginx request logs ate up all the disk space, which caused an issue with Redis. Cleared out all the logs, and everything returned to normal. Also been wanting to cache on the edge more with Cloudflare, but this would have to likely be done with the new Workers product, because the shortest time you can cache is ~2 hours.

![cloudflare](https://i.imgur.com/hkNDUAq.png)

![cloudflare2](https://imgur.com/AT6EjmE.png)

Going to reach out to DigitalOcean and see if they can gift us a small Kubernetes cluster for the project going forward, or just a beefier VM in general. 

However this doesn't address the slow database issue. The slowness likely has to do with the low tier MongoDB Atlas cluster everything runs on. The lowest tiers use shared  CPU and RAM, so I don't have any insights into the cluster performance unfortunately.

Cheapest dedicated cluster is ~$60 a month, which is cost prohibitive for a project of this size. I'll reach out to MongoDB, not sure I've seen them sponsor things though.

**Comment by Tearth** [comment]
Thanx for the explanation, now I understand the situation. I'm not sure if I should close this issue, so you decide.

**Comment by jakewmeyer** [comment]
Closing since the immediate issue is resolved 👍
