### ISSUE TITLE
Launch site is now a unique identifier vs name

### ISSUE THREAD

**Issue by waterskier2007** [r-spacex/SpaceX-API#26]
Is there a reason for this change? It makes some sense, but there is no no "friendly" name provided for each launch site in the launches endpoint

https://api.spacexdata.com/launches

**Comment by jakewmeyer** [comment]
I changed it in #21 for consistency's sake

Potential solution would be to have two options
```json
"launch_site_id": "kwajalein_atoll",
"launch_site": "Kwajalein Atoll"
```

**Comment by waterskier2007** [comment]
That makes sense. Would it be possible to do a join when fetching the data and then actually return a full launch site object for each launch in the launches endpoint

**Comment by jakewmeyer** [comment]
Working on that currently for launch sites, payloads, and links for each launch

**Comment by waterskier2007** [comment]
nice

**Comment by jakewmeyer** [comment]
**Update**

So I've decided to transition the data over to MongoDB for flexibility going forward. The joins weren't giving me what I wanted, and it makes more sense with dynamic data like this.

This should give better flexibility in regards to multiple payloads, links, launch sites, etc... Instead of jumping through lots of SQL joins in order to achieve similar results. This should allow for more agile modeling as new ideas + data come forward.

So the new schema for launches will look similar to the following:
```json
{
    "flight_number": 1,
    "launch_year": "2006",
    "launch_date_utc": "2006-03-24T22:30:00Z",
    "launch_date_local": "2006-03-25T10:30:00+12:00",
    "rocket": "Falcon 1",
    "rocket_type": "Merlin A",
    "core_serial": "Merlin 1A",
    "cap_serial": null,
    "launch_site": {
      "site_id": "kwajalein_atoll",
      "site_name": "Kwajalein Atoll"
    },
    "payloads": [
      {
        "payload_id": "FalconSAT-2",
        "customer": "DARPA",
        "payload_type": "Satelite",
        "payload_mass_kg": 20,
        "payload_mass_lbs": 43,
        "orbit": "LEO"
      }
    ],
    "launch_success": false,
    "reused": false,
    "land_success": false,
    "landing_type": null,
    "landing_vehicle": null,
    "links": {
      "mission_patch": "http://spacexpatchlist.space/images/thumbs/falcon_1_flight_1.png",
      "article_link": "https://www.space.com/2196-spacex-inaugural-falcon-1-rocket-lost-launch.html",
      "video_link": "https://www.youtube.com/watch?v=0a_00nJ_Y88"
    },
    "details": "Engine failure at 33 seconds and loss of vehicle"
  },
```

Hoping to make the transition in the next day or so, all the new code is written and tested, just have a few more things to double check before it merges. 👍

**Comment by jakewmeyer** [comment]
Production server is officially switched over to Mongo, working on updating all the launches to the new schema

**Comment by waterskier2007** [comment]
That all looks good, but one thing that has changes is that https://api.spacexdata.com/launchpads now returns an array as the base object. It's an array, with one dictionary that has launchpads and test_locations... How come the root object is an array, it should just be a dictionary.

**Comment by jakewmeyer** [comment]
Should be corrected now 👍

**Comment by waterskier2007** [comment]
All good. Nice work man!
