### ISSUE TITLE
Wrong order of next launches

### ISSUE THREAD

**Issue by xhardcorex** [r-spacex/SpaceX-API#277]
I have noticed some bugs:
https://api.spacexdata.com/v3/launches/upcoming
- that the data of response  contains some launches with wrong date 01.01.19 
- there are launches in the response not sorted by date descending. 
https://api.spacexdata.com/v3/launches/next
- one of the launch contains date(upcoming) 01.12.19 but in the response of the next  launch the date is 04.12.19 . 
Will wait your reply! Thank You!

**Comment by jakewmeyer** [comment]
See [Date field FAQ's](https://docs.spacexdata.com/?version=latest#intro) in the docs introduction for more info on this.

TLDR The flight number is the only correct way to sort these launches, because the dates can represent partial dates. Because of this, a few more context fields are provided to aid in displaying the dates correctly.
