### ISSUE TITLE
Issues regarding fairing information

### ISSUE THREAD

**Issue by jesusrp98** [r-spacex/SpaceX-API#281]
In upcoming flights, the information inside the `fairing` block seems misunderstanding.

Both the `reused` tag & `recovery_attempt` seems to be always `false`. This was ok when SpaceX didn't reuse the fairing. But now they're taking it seriously. This behavior should be corrected, by setting this to `null` by default, if no information is known.

**Comment by jakewmeyer** [comment]
Agreed. 

Another necessary tweak is changing `ship` to `ships`, and making it an array, since we now have multiple fairing recovery ships.

Should recovered be nullable too? 

If so, the new behavior would be as follows:

If a launch won't have fairings, the default is:
```json
{
  "fairings": null
}
```

If a launch will have fairings:
```json
{
  "fairings": {
    "reused": null,
    "recovery_attempt": null,
    "recovered": null,
    "ships": []
  } 
}
```

**Comment by jesusrp98** [comment]
This new behavior would be much nicer.

The only thing that could be troublesome is renaming `ship` to `ships`: that could break some apps. I personally don't mind it since I don't use them. What do you think about it?

**Comment by jakewmeyer** [comment]
I'll keep the current ship behavior for now 👍 

All upcoming launches are updated for the new behavior

**Comment by jesusrp98** [comment]
Great. Thanks!
