### ISSUE TITLE
Starlink 5 missing launch_site data

### ISSUE THREAD

**Issue by timisenman** [r-spacex/SpaceX-API#291]
All three values are currently set to null. I imagine this is because that information doesn't exist yet. If possible, can assume it's Cape Canaveral, and change it when we receive new data? 

I made this mistake of assuming this data would be available, so versions of my app (the majority of them) are crashing when receiving a null value. I've fixed it in a new build, but it would be helpful for older versions. 

Thanks 🙏🏼

**Comment by Tearth** [comment]
Same here, looking at https://www.reddit.com/r/spacex/wiki/launches/manifest it seems that Starlink 5 has launch site set to "SLC-40, LC-39A" (maybe parser can't handle a situation when there are two possible launch sites set, maybe it should just pick the first one because launch_site isn't an array).

**Comment by jakewmeyer** [comment]
Going to fix this over the weekend. Currently the checks are hardcoded, which doesn't lend well to human input 🙃 

A more flexible regex like the ones for dates should work better there

**Comment by jakewmeyer** [comment]
This is fixed in the v4 updater
