### ISSUE TITLE
launches/next returns launch in the past

### ISSUE THREAD

**Issue by x70b1** [r-spacex/SpaceX-API#318]
I used the `https://api.spacexdata.com/v3/launches/next` endpoint.
It gives me the launch date `01.05.2020`for Starlink7. But this value is in the past.

I know that the data for this comes from reddit. So there seems to be no exact launch date yet. 

The question for me here is: Shouldn't `launches/next` return a launch that already has a date?
This would lead me to the `DM-2` mission. If Starlink 7 got newer data, the reponse could be change.

**Comment by jakewmeyer** [comment]
This has to do with the way we store partial dates.

At the time, the reddit date was `2020 May TBA`. Because no time was available yet, it defaults to the first of the month.

To help out with this, we include the `tentative_max_precision` field, that shows the precision of the date. In this case it would've been  `"tentative_max_precision": "month"`, which means that the date is precise down to the `month` level.

Other possible values are `year`, `half`, `quarter`, `month`, `day`, and `hour`. Most people tend to create a date parser for each level of precision, and then direct the flow depending on the precision value.

**Comment by x70b1** [comment]
That clears up things, thanks!
Then I have to check the precision first.
