### ISSUE TITLE
Revised History endpoints

### ISSUE THREAD

**Issue by jakewmeyer** [r-spacex/SpaceX-API#360]
@jesusrp98 Feel free to post any thoughts in here about possible schemas + an update strategy.

**Comment by jesusrp98** [comment]
I'll do this in the coming days, making it ready this next week @jakewmeyer !

**Comment by jesusrp98** [comment]
FYI I'll be gathering information from the 'Achievements' section of [SpaceX's Wikipedia page](https://en.wikipedia.org/wiki/SpaceX).

**Comment by jesusrp98** [comment]
Hey, news update! I'm sorry this feature took so long to implement, but it's finallly done.

Attached to this comment are the new achievements that will replace the ones in the v3 of the API.
Take a look @jakewmeyer and let me know if everything's OK!

I can open issues once the Wikipedia adds new achievements to the page, in order to add them to the endpoint.

[File](https://github.com/r-spacex/SpaceX-API/files/5250028/achiv-v4.txt)

**Comment by jesusrp98** [comment]
Any news about this @jakewmeyer ?

**Comment by jakewmeyer** [comment]
Looks good to me 👍 

I'll get these added shortly

**Comment by jakewmeyer** [comment]
Added and live 👍 Let me know if you find any issues
