### ISSUE TITLE
Queries return Mongo ID's instead of populating them

### ISSUE THREAD

**Issue by PiotrRut** [r-spacex/SpaceX-API#364]
Is this desired/expected behaviour or something that's still in progress?

**Comment by PiotrRut** [comment]
Also would be nice to get my website added to the list if you've got a while :) 
http://spacex.prutkowski.tech

**Comment by jakewmeyer** [comment]
Yes, this is expected behavior.

The rationale is flexibility. As you start to populate things, the size of the payload gets bigger and bigger, which might be undesirable in some applications, especially if you only care about a field or two at the top level.

That way if I only need all the launch `name` fields, I still get a fast query instead of being forced to wait for all the populate queries to finish, yet it allows others to customize to the population level they want.

Happy to add it  👍

**Comment by jakewmeyer** [comment]
Added in 53e6db211dfc0b26bb0c650312543a0e870ea4aa
