### ISSUE TITLE
Starlink-10 (v1.0) & SkySat 19-21 Flight #100 Wrong Date

### ISSUE THREAD

**Issue by waruss321** [r-spacex/SpaceX-API#382]
Can't see this launch listed anywhere, think it has the wrong date

**Comment by jakewmeyer** [comment]
Currently the launch is slated for `2020 July`, so this has to do with the way partial dates are stored.

See `date_precision` to see how much of the date is valid. In this case, because the precision is `month`, it's only valid to `2020-07`. Possible values for this include `half`, `quarter`, `year`, `month`, `day`, and `hour`.

```json
{
    "date_utc" : "2020-07-01T00:00:00.000Z", 
    "date_precision" : "month", 
}
```

Looks like I forgot to move the bit about this from the v3 docs to the v4 docs. I'll get that fixed.

**Comment by 414412** [comment]
when speacx lunch again

**Comment by waruss321** [comment]
Ah I see, thank you for the clarification 👍
