### ISSUE TITLE
Question: What defines a launch as TBD? 

### ISSUE THREAD

**Issue by timisenman** [r-spacex/SpaceX-API#490]
The next launch (Starlink 12) was initially set as `"tbd": true` but switched last night to `false`, even though the date is still not set. 

I assume that TBD is used when a launch doesn't have a date, so I format the data in my app that way, but I wanted to ask to make sure my understanding was correct (or not). Want to make sure I'm showing my users the right info.

Thanks!

**Comment by jakewmeyer** [comment]
It's purely a cosmetic boolean right now, mostly because it's used inconsistently by SpaceX and the community. 

Starlink 12 was flagged `TBD` because the wiki had the date `2020 Sep TBA`. If the date contains `TBD` or `TBA`, it's flagged as `tbd`.

I'm open to adding more logic to flag things as TBD, but the definition is kinda fuzzy currently. If we can nail down a definition that most people agree with, I'm happy to add it 👍

**Comment by timisenman** [comment]
Okay, dope! Glad it wasn't just me lol.

The logic I use in Pocket Rocket is "If launchDate < CurrentDate && upcoming == true { tbd = true }" 
So, even if TBD is false, but the date is something like right now where the launch date is Sep 1 but today is Sep 20, and the launch is still upcoming, then just show it is TBD. 

Curious if others do the same, or if anyone has better proposals.

**Comment by jesusrp98** [comment]
I preffer using the `datePrecision` field. If the precision != `hour`, then the date is 'TBD'.

**Comment by timisenman** [comment]
That's a nice solution too @jesusrp98. 

@jakewmeyer is it always the case that a launch's `datePrecision` will be within an hour? How is that attribute decided?

**Comment by jakewmeyer** [comment]
`datePrecision` is set by some Regex patterns checking wiki dates.
