### ISSUE TITLE
Launches empty or internal server errors on endpoints (V3)

### ISSUE THREAD

**Issue by jeroenboumans** [r-spacex/SpaceX-API#564]
I'm retrieving empty arrays or server errors on V3 launches endpoints:
* https://api.spacexdata.com/v3/launches/next (internal server error)
* https://api.spacexdata.com/v3/launches/upcoming (empty results)

**Comment by jakewmeyer** [comment]
This is due to the V3 deprecation plan. The plan was after a certain date, V3/V2 would no longer receive new data updates, to gently push people over to V4. The links will remain active as long as the project exists, but no data will be updated. 

It was originally slated for the end of September, but was pushed to November to give people adequate time to update to V4. The final cutoff time was Nov 7th, but I've waited a but past that  just to make sure no last minute needs came in. 

I went and removed all the upcoming launches in V3, which is causing this issue. I can adjust the error presented, or add back one upcoming launch, but it's more of a band-aid fix.

**Comment by jeroenboumans** [comment]
@jakewmeyer I wasn't aware about the deprecation plan until yesterday. Would it be possible to extend this period for another week? This might give me some time on fixing this issue since I've to rewrite request logic. Currently, about 8k end users do not have launches feeds visible in my application.

I would very much appreciate if the deprecation period could be extended somehow.

**Comment by koxm** [comment]
Shortly after the release of the SpaceX Module for MagicMirror I also released a module based on the SpaceLaunchNow api. And personally I like it much better because it also shows other agencys. Is that also an option for you?

It's over here: https://spacelaunchnow.me/api/3.3.0

**Comment by jakewmeyer** [comment]
@jeroenboumans Sorry for the delay, I just backfilled the previous launches, and added two of the upcoming launches back.

**Comment by jeroenboumans** [comment]
@jakewmeyer no worries and thank you, I could prevent the impact on my side by switching the launches endpoints from V3 to V4. Since the structure in querying has changed this took me two evenings to rewrite this. I was planning to switch eventually but was't aware of the changes since I haven't got the time to update my app lately. 

Is it possible to introduce a notification system where you can subscribe as a developer (by email for example) for being notified when API version change in structure or when endpoints will be deprecated soon?

@koxm thanks for the tip! Although that would take me some more time to fix the initial problem. ;) I just needed to fix this for my users in the shortest time possible.

**Comment by jakewmeyer** [comment]
Best solution currently would be to watch the repo to get notifications for releases. Going forward, all breaking changes including deprecations would be announced there.

**Comment by jeroenboumans** [comment]
Okay Jake, thanks!
