### ISSUE TITLE
Starlink 16 Livestream not added when live

### ISSUE THREAD

**Issue by russelltwarwick** [r-spacex/SpaceX-API#652]
Not sure if there is an issue with appending the livestream to the launch. Something might have broke? 🤷🏻‍♂️

**Comment by jakewmeyer** [comment]
Some issue with the webcast update job, not sure why it didn't pick up the one from this morning. Also might have to do with how we check for new livestreams. Due to quota restrictions and a terrible youtube api we can only check once an hour for new webcasts.

Going to go the youtube RSS route instead, so we can check more often. should be able to get that done over the weekend.

**Comment by jakewmeyer** [comment]
Officially checking the rss feed now every 5 min for the livestreams now. Should be much more reliable now.
