### ISSUE TITLE
Little tweaks that would be useful or things I noticed

### ISSUE THREAD

**Issue by coopstercoop** [r-spacex/SpaceX-API#7]
First of nice work with the API. Haven't worked too much with Ruby, so not sure if I'd be much help on the tech side (more a .NET dev), though considering making a Windows app (desktop, mobile, xbox).

Little tweaks that would be useful or things I noticed:

- Setting up https://api.spacexdata.com/vehicles/ to return a list of vehicles would be useful
- Falcon 1 seems to be missing
- https://api.spacexdata.com/sites has a list of vehicles, but just looks to be a string. Should this be a list?
- A link between different objects. E.g. Finding the launch site from a launch isn't straight forward (match "CCAFS LC-40" from a launch to "Space Launch Complex 40" in site)

Like I said above, I'm more a .NET dev, but if you want to bounce any ideas or problems of me let me know. My day job is working with MVC WebAPI. Nice work :)

**Comment by jakewmeyer** [comment]
Thanks for the feedback. It's nice that API's are generally platform agnostic, so anyone can easily contribute, regardless of programming language. Universal data! 👍 

Regarding the tweaks,

* Planning on allowing /vehicles to show the full list, waiting on an open pull request to finish some edits so I can merge and finish that.

* Absolutely right about Falcon 1 being missing. I'm doing some digging to compile information to add a section for it.

* It should be a list, I think I left it as a string originally because only one type of rocket is being launched currently. I'll change it to allow for better expansion. Actually in the process of revamping the sites info to have more detail, especially on the individual launchpads, similar to [This page](https://www.reddit.com/r/SpaceX/wiki/pads)

* Agreed. Consistency across the different results is key. When I revise the site data, I'll update it to match the rest of the data. 

I appreciate the feedback, and I'll keep you updated on the fixes as I add them. If I run into any issues or have any other ideas, I'll be sure to reach out 👍

**Comment by jakewmeyer** [comment]
Site data is now under the endpoint
```http
https://api.spacexdata.com/launchpads
```

**Comment by jakewmeyer** [comment]
Just to update this issue, only thing left to do is get Falcon 1 data together and in the api

**Comment by jakewmeyer** [comment]
Falcon 1 data has been added as of fe195477fb07139c23ab567c36d247267874c4cb

**Comment by coopstercoop** [comment]
Cool, got a bit of spare time in the  coming week to have a proper go at connecting it up. Thanks

Sent from my Windows 10 phone
