### ISSUE TITLE
Core serials differ between launch data and core lookup

### ISSUE THREAD

**Issue by waterskier2007** [r-spacex/SpaceX-API#70]
disclaimer: might be the same for capsules

example

https://api.spacexdata.com/v2/launches/latest

The core serial is listed as B1032.2 but if you then hit https://api.spacexdata.com/v2/parts/cores/B1032.2

It's incorrect. The serial is actually B1032

If it makes sense to suffix the serial with a .X for number of flights, that could be a separate field.

**Comment by jakewmeyer** [comment]
Looks like the latest launches core serial was a mistake, I haven't been listing the number of reuses in the core serial, since it would make a unique number each time, making it harder to compare against.

We could add a new field for the number of previous flights of the core for each launch, but the data should already be in the detailed core data.

**Comment by waterskier2007** [comment]
@jakewmeyer ok, Just che

**Comment by waterskier2007** [comment]
@jakewmeyer ok, just checked and it looks good now. I'll leave the decision about reuse numbers up to you.

**Comment by jakewmeyer** [comment]
I'll go ahead and add it in the core section for each launch, I think it's valuable info to have 👍

**Comment by petrosh** [comment]
`flown`?

**Comment by jakewmeyer** [comment]
Flown sounds more like a boolean value though, instead of an incremental amount. Maybe `flights`?

**Comment by petrosh** [comment]
`flights` is great 👍

**Comment by jakewmeyer** [comment]
Added the field for past and upcoming launches, slight adjustment from `flights` to `flight` for clarity 👍
