### ISSUE TITLE
endpoints are down right now

### ISSUE THREAD

**Issue by datu925** [r-spacex/SpaceX-API#87]
Not sure if an issue is the right medium to flag this, but I don't see any other ways to do it. I've tried the https://api.spacexdata.com/v2/launches/ and https://api.spacexdata.com/v2/rockets endpoints and both return 503 errors after a fairly lengthy delay. I've tried from multiple devices and browsers.

**Comment by garyjacobs** [comment]
I'm getting the same thing!
"UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.})"

**Comment by jakewmeyer** [comment]
Looks like a database issue, looking into this

**Comment by jakewmeyer** [comment]
Should be back up and running on a new cluster with a backup from last week, working on getting the rest of the data up to date

**Comment by jakewmeyer** [comment]
Still working on a postmortem of the old cluster, really not clear why it went down in the first place

**Comment by datu925** [comment]
Looks good to me! Thanks for the quick response. I can close this issue if helpful - let me know.

**Comment by garyjacobs** [comment]
"mission_name": "", has dropped off but you did say you were working on getting the rest of the data up to date, flagging just in case. Thanks again Jake.

**Comment by jakewmeyer** [comment]
Mission name should be back now. Was able to pull a latest backup, but the queries are running extremely slow, sometimes takes 5min or so to complete. 

Regardless, as of now the data should be 100% up to date and available 👍

**Comment by jakewmeyer** [comment]
I'll keep this issue open for now, until I have a clear answer on what happened.

**Comment by jakewmeyer** [comment]
Finally have a root cause for the database issue. The lower tiers of MongoDB Atlas have a bandwidth cap equal to double the max storage space on the instance. In our case, we had a 1GB in and out cap on the database traffic. When you hit the limit, the network connection for the instance is throttled down to 1KB/s, and it usually needs 50KB/s+ to handle the current traffic load. So now the database is running on an M2 instance instead of M0, and has a 4GB cap now instead of 1GB.

This likely stemmed from my decision to stop caching the launches endpoint so updates could be received immediately. We were likely borderline on bandwidth for awhile, but that pushed it over the edge.

Thanks for your patience! 👍
